<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '507b4d17fff59c1991d8e50cc1af5365',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://mail.apresbac.ma:465?encryption=ssl&auth_mode=login&username=no-reply@apresbac.ma&password=U+kf@g*1&cH',
  'DATABASE_URL' => 'mysql://apresbac_prod_user:_kyM$g6u!1D5@127.0.0.1:3306/apresbac_prod?serverVersion=10.6.12-MariaDB&charset=utf8mb4',
);
